/*
 * AKKBLFPIM23Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.AttributeController;
const AuthentificationByRefreshTokenRequest = testerlib.AuthentificationByRefreshTokenRequest;
const AuthentificationByPasswordRequest = testerlib.AuthentificationByPasswordRequest;


describe("AttributeController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Assuming that the given code is the code of an existing attribute
     */
    it("should testAttribute response", function testAttributeTest(done) {
        controller.getAttribute(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

    /**
     * TODO: Add Description
     */
    it("should testAttributes response", function testAttributesTest(done) {
        controller.getAttributes(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });
});
