/*
 * AKKBLFPIM23Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.AttributeGroupsController;
const AuthentificationByRefreshTokenRequest = testerlib.AuthentificationByRefreshTokenRequest;
const AuthentificationByPasswordRequest = testerlib.AuthentificationByPasswordRequest;


describe("AttributeGroupsController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Assuming that the given code is the code of an existing attribute group
     */
    it("should testAttributeGroup2XOnly response", function testAttributeGroup2XOnlyTest(done) {
        controller.getAttributeGroup2XOnly(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

    /**
     * TODO: Add Description
     */
    it("should testAttributeGroups2XOnly response", function testAttributeGroups2XOnlyTest(done) {
        controller.getAttributeGroups2XOnly(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });
});
