/*
 * AKKBLFPIM23Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */
 'use strict';

const chai = require('chai');
const assert = chai.assert;
const TestHelper = require("../TestHelper");
const APIHelper = require("../../lib/APIHelper");
const testerlib = require("../../lib");
const testConfiguration = require("../TestBootstrap");

const controller = testerlib.FamilyVariant2XOnlyController;
const AuthentificationByRefreshTokenRequest = testerlib.AuthentificationByRefreshTokenRequest;
const AuthentificationByPasswordRequest = testerlib.AuthentificationByPasswordRequest;


describe("FamilyVariant2XOnlyController Tests", function tests() {
    this.timeout(testConfiguration.TEST_TIMEOUT);

    /**
     * Assuming that the given codes are respectively the code of an existing family and an existing family variant
     */
    it("should testFamilyVariant2XOnly response", function testFamilyVariant2XOnlyTest(done) {
        controller.getFamilyVariant2XOnly(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });

    /**
     * TODO: Add Description
     */
    it("should testFamilyVariants2XOnly response", function testFamilyVariants2XOnlyTest(done) {
        controller.getFamilyVariants2XOnly(function callback(error, response, context) {
            // test response code
            assert.equal(200, context.response.statusCode);
            done();
        });
    });
});
