/**
 * AKKBLFPIM23Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const AuthentificationByRefreshTokenRequest =
  require('../lib/Models/AuthentificationByRefreshTokenRequest');
const AuthentificationByPasswordRequest =
  require('../lib/Models/AuthentificationByPasswordRequest');

const classMap = {
    AuthentificationByRefreshTokenRequest,
    AuthentificationByPasswordRequest,
};

/**
 * Factory class to create instances of models and exception classes
 */
class ModelFactory {
    /**
     * Creates instance of a model class
     * @param  modelName  {string}  Name of class to instantiate
     * @returns  {object} Instance of the model class
     */
    static getInstance(modelName) {
        return new classMap[modelName]();
    }
}

module.exports = ModelFactory;
