/**
 * AKKBLFPIM23Lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

'use strict';

const Servers = {

    /**
     * TODO: Write general description for this element
     */
    AKK: 'AKK',

};

module.exports = Servers;
